# Generated by Django 5.0.6 on 2026-04-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_days', models.PositiveIntegerField(default=30)),
                ('require_pin', models.BooleanField(default=False)),
                ('portal_base_url', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Invite Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_submission', models.BooleanField(default=True)),
                ('on_kyc_complete', models.BooleanField(default=True)),
                ('on_revision', models.BooleanField(default=False)),
                ('digest_email', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
            },
        ),
    ]
