# Generated by Django 5.0.6 on 2026-04-22 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('employment_contract', 'employment_contract'), ('payslips', 'payslips'), ('identity', 'identity'), ('home_address', 'home_address'), ('office_address', 'office_address'), ('social_media', 'social_media'), ('contact_details', 'contact_details'), ('next_of_kin', 'next_of_kin')], db_index=True, max_length=30)),
                ('old_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], max_length=25)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='applicants.applicant')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Log Entry',
                'verbose_name_plural': 'Review Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
