# Generated by Django 5.0.6 on 2026-04-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='section_name',
            field=models.CharField(choices=[('employment_contract', 'employment_contract'), ('payslips', 'payslips'), ('identity', 'identity'), ('home_address', 'home_address'), ('office_address', 'office_address'), ('social_media', 'social_media'), ('contact_details', 'contact_details'), ('next_of_kin', 'next_of_kin'), ('referred_by', 'referred_by')], db_index=True, max_length=30),
        ),
    ]
