# Generated by Django 5.0.6 on 2026-04-22 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('ADMIN', 'Admin/HR'), ('APPLICANT', 'Applicant')], db_index=True, max_length=10)),
                ('recipient_id', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('applicant_id', models.CharField(blank=True, default='', max_length=50)),
                ('section_name', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='notificatio_recipie_cbf482_idx')],
            },
        ),
    ]
