# Generated by Django 5.0.6 on 2026-04-22 07:10

import django.db.models.deletion
import documents.models
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_primary', models.CharField(max_length=20, validators=[documents.validators.validate_kenyan_phone])),
                ('phone_secondary', models.CharField(blank=True, max_length=20, validators=[documents.validators.validate_kenyan_phone])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=documents.models.employment_contract_upload_path, validators=[documents.validators.validate_file_size, documents.validators.validate_file_extension])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Employment Contract',
                'verbose_name_plural': 'Employment Contracts',
            },
        ),
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_text', models.TextField()),
                ('google_maps_pin_url', models.URLField(max_length=500, validators=[documents.validators.validate_google_maps_url])),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Home Address',
                'verbose_name_plural': 'Home Addresses',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kra_pin_file', models.FileField(upload_to=documents.models.identity_upload_path, validators=[documents.validators.validate_file_size, documents.validators.validate_file_extension])),
                ('national_id_file', models.FileField(upload_to=documents.models.identity_upload_path, validators=[documents.validators.validate_file_size, documents.validators.validate_file_extension])),
                ('kra_pin_number', models.CharField(help_text='Format: A000000000A', max_length=11, validators=[documents.validators.validate_kra_pin])),
                ('id_number', models.CharField(help_text='7–8 digit Kenyan National ID number', max_length=8, validators=[documents.validators.validate_id_number])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Identity Document',
                'verbose_name_plural': 'Identity Documents',
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('CHILD', 'Child'), ('OTHER', 'Other')], max_length=20)),
                ('relationship_other', models.CharField(blank=True, help_text='Specify if relationship is "Other".', max_length=100)),
                ('phone_primary', models.CharField(max_length=20, validators=[documents.validators.validate_kenyan_phone])),
                ('phone_secondary', models.CharField(blank=True, max_length=20, validators=[documents.validators.validate_kenyan_phone])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
            },
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_text', models.TextField()),
                ('google_maps_pin_url', models.URLField(max_length=500, validators=[documents.validators.validate_google_maps_url])),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Office Address',
                'verbose_name_plural': 'Office Addresses',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.payslip_upload_path, validators=[documents.validators.validate_file_size, documents.validators.validate_file_extension])),
                ('month_label', models.CharField(help_text='e.g. "March 2025"', max_length=20)),
                ('is_certified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['month_label'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook_url', models.URLField(blank=True, max_length=300, validators=[documents.validators.validate_facebook_url])),
                ('instagram_url', models.URLField(blank=True, max_length=300, validators=[documents.validators.validate_instagram_url])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media Entries',
            },
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('applicant', 'month_label'), name='unique_payslip_per_month'),
        ),
    ]
