# Generated by Django 5.0.6 on 2026-04-24 11:10

import django.db.models.deletion
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300, validators=[documents.validators.validate_linkedin_url]),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='relationship_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ReferredBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=25)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_relationship', models.CharField(max_length=100)),
                ('referrer_phone', models.CharField(blank=True, max_length=20, validators=[documents.validators.validate_kenyan_phone])),
                ('referrer_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Referred By',
                'verbose_name_plural': 'Referred By Entries',
            },
        ),
    ]
